### ISSUE TITLE
 No module named 'profil3r.core'

### ISSUE THREAD

**Issue by zolopp** [amitrajputfff/Profil3r#1]
hello,
may i konw how to fixed this problme?

**os:**kali
**issues**:

Traceback (most recent call last):
  File "profil3r.py", line 3, in <module>
    from profil3r.core import Core
  File "/home/pi/Profil3r/profil3r.py", line 3, in <module>
    from profil3r.core import Core
ImportError: No module named 'profil3r.core'; 'profil3r' is not a package

**Comment by igorkolev** [comment]
same for me

**Comment by Katano22** [comment]
yep same here

**Comment by Katano22** [comment]
hello friend 
i was just curious about if u could fix the problem? did u?

**Comment by igorkolev** [comment]
Steel not

**Comment by Hendrik7889** [comment]
any updates

**Comment by raf181** [comment]
still does not work

same error

**Comment by lmgtrigo** [comment]
same problem

**Comment by tolstoy88** [comment]
the same problem

**Comment by Climax6666** [comment]
Same here, any news ?

**Comment by carbomb348** [comment]
any update?

**Comment by Katano22** [comment]
> any update? 
> 

Sadly, no.

**Comment by faygoclub** [comment]
same here

**Comment by v3n0m30** [comment]
same here

**Comment by roger648** [comment]
same, anyone solved?

**Comment by pantherXop** [comment]
> same, anyone solved?

no

**Comment by fedecatt** [comment]
same, anyone solved?

**Comment by txbuff** [comment]
so this shit just doesnt work cause of the error that noone will answer with a fix

**Comment by amitrajputfff** [comment]
Well we have chatgpt now , i will try to fix the error soon. Its because
the module is deprecated now.

*Amit Rajput*
